# Generated by Django 5.1.2 on 2024-10-13 17:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Running', 'Running'), ('Cycling', 'Cycling'), ('Weightlifting', 'Weightlifting'), ('Swimming', 'Swimming'), ('Walking', 'Walking')], max_length=50)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in kilometers (if applicable)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('calories_burned', models.PositiveIntegerField(help_text='Calories burned during the activity', validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(help_text='Month of the year (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(help_text='Year of the activity', validators=[django.core.validators.MinValueValidator(2000)])),
                ('total_activities', models.PositiveIntegerField(default=0)),
                ('total_distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_calories_burned', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-total_activities'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
