# Generated by Django 5.1.2 on 2024-10-13 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers (optional for non-distance activities)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
